<?php

declare(strict_types=1);

namespace Darangonaut\DoctrineProjections\Tests\Feature;

use Darangonaut\DoctrineProjections\ProjectionsServiceProvider;
use Darangonaut\DoctrineProjections\Tests\EntityManagerFactory;
use Doctrine\ORM\EntityManagerInterface;
use Illuminate\Support\Facades\File;
use Illuminate\Testing\PendingCommand;
use Orchestra\Testbench\TestCase;
use PHPUnit\Framework\Attributes\Test;

/**
 * How the commands behave when the flags or the database are not in the
 * state the happy path assumes.
 */
final class CommandCombinationsTest extends TestCase
{
    private string $output;

    private string $migrations;

    /** @return list<class-string> */
    protected function getPackageProviders($app): array
    {
        return [ProjectionsServiceProvider::class];
    }

    protected function defineEnvironment($app): void
    {
        $this->output = sys_get_temp_dir().'/projections-combos-'.getmypid();
        $this->migrations = sys_get_temp_dir().'/migrations-combos-'.getmypid();

        $app['config']->set('doctrine-projections.namespace', 'Generated\\Combos');
        $app['config']->set('doctrine-projections.path', $this->output);
        $app['config']->set('doctrine-projections.diff.path', $this->migrations);

        $app->singleton(
            EntityManagerInterface::class,
            static fn (): EntityManagerInterface => EntityManagerFactory::forFixtures('Entities'),
        );
    }

    protected function tearDown(): void
    {
        File::deleteDirectory($this->output);
        File::deleteDirectory($this->migrations);

        parent::tearDown();
    }

    private function command(string $command): PendingCommand
    {
        $pending = $this->artisan($command);

        self::assertInstanceOf(PendingCommand::class, $pending);

        return $pending;
    }

    /**
     * `--check` asks a question about files on disk; `--dry` is about not
     * writing any. Checking wins, and nothing is written either way.
     */
    #[Test]
    public function check_wins_over_dry_and_neither_writes(): void
    {
        $this->command('doctrine:projections --dry --check')->assertFailed();

        self::assertDirectoryDoesNotExist($this->output);
    }

    #[Test]
    public function check_still_passes_when_combined_with_dry_after_generating(): void
    {
        $this->command('doctrine:projections')->assertSuccessful();
        $this->command('doctrine:projections --dry --check')->assertSuccessful();
    }

    #[Test]
    public function a_diff_against_an_empty_database_creates_every_table(): void
    {
        $this->command('doctrine:diff --dry')
            ->expectsOutputToContain('CREATE TABLE')
            ->assertSuccessful();
    }

    /**
     * Nothing was migrated in between, so the second run must describe the
     * same change — a diff that drifts on its own would mean the mapping
     * is being read differently each time.
     */
    #[Test]
    public function two_diffs_without_migrating_describe_the_same_change(): void
    {
        $this->command('doctrine:diff --name=first')->assertSuccessful();
        $this->command('doctrine:diff --name=second')->assertSuccessful();

        $files = array_values(array_filter(File::glob($this->migrations.'/*.php'), is_string(...)));

        self::assertCount(2, $files);

        $statements = array_map(
            static fn (string $file): string => preg_replace('/^.*Generated by.*$/m', '', File::get($file)) ?? '',
            $files,
        );

        self::assertSame(
            str_replace('first', '', $statements[0]),
            str_replace('second', '', $statements[1]),
            'the same mapping and the same database must yield the same SQL',
        );
    }
}
